#pragma once
#define PIN_IMU_CS 17
#define PIN_ANALOG_VOLTAGE 27
#define PIN_ANALOG_CHARGE_VOLTAGE 26
#define PIN_ANALOG_CHARGE_CURRENT 28

#define PIN_GPS_POWER 22
#define PIN_ESC_POWER 20
#define PIN_RASPI_POWER 21

#define PIN_EMERGENCY_1 7
#define PIN_EMERGENCY_2 6
#define PIN_EMERGENCY_3 3
#define PIN_EMERGENCY_4 2

#define PIN_MUX_IN 11
#define PIN_MUX_OUT 12
#define PIN_MUX_ADDRESS_0 13
#define PIN_MUX_ADDRESS_1 14
#define PIN_MUX_ADDRESS_2 15