[system]
compatible=openmower-cm4
bootloader=custom
statusfile=/data/rauc/status.ini

[keyring]
path=/etc/rauc/keyring.pem

[handlers]
bootloader-custom-backend=/usr/lib/rauc/tryboot-backend

[slot.boot.0]
device=/dev/mmcblk0p2
type=vfat
bootname=A

[slot.rootfs.0]
device=/dev/mmcblk0p5
type=raw
parent=boot.0

[slot.boot.1]
device=/dev/mmcblk0p3
type=vfat
bootname=B

[slot.rootfs.1]
device=/dev/mmcblk0p6
type=raw
parent=boot.1
